### ISSUE TITLE
Alf training is slower than original tfagents (it cost  more time for one training step )

### ISSUE THREAD

**Issue by witwolf** [HorizonRobotics/alf#100]
i tried several groups experiments with almost the same configurations (same network parameters , hyper-parameter ... and  without tensorboard summaries except basic metrics )
the results show that alf cost more time 

ddpg cost more than 2x times ,and sac cost about 4~5x times

<img alt="" height="365" src="https://user-images.githubusercontent.com/1267359/60976519-677ddb00-a360-11e9-90af-75a7a2485c73.png">

**Comment by emailweixu** [comment]
I can understand ddpg and sac can be twice as slow as tfagents, because for mini_batch_length=2, computation cost are doubled. Currently, this can be alleviated by using a larger mini_batch_length and correspondingly smaller mini_batch_size. And this won't be a big issue for RNN as we will need to use a larger value for mini_batch_length.

But I don't understand why sac is more than twice as slow as tf-agent.

**Comment by emailweixu** [comment]
And it looks to me that alf ddpg still cannot train to the same level of episode return as tfagents. Still need to investigate.

**Comment by witwolf** [comment]
> And it looks to me that alf ddpg still cannot train to the same level of episode return as tfagents. Still need to investigate.

performance are almost the same   when set `NUM_PARALLEL_ENVIRONMENTS=1`
i run exps with grid_search 

	python -m alf.bin.grid_search \
	  --root_dir=~/tmp/ddpg \
	  --search_config=ddpg_grid_search.json \
	  --gin_file=ddpg_pendulum.gin \
	  --gin_param='NUM_PARALLEL_ENVIRONMENTS=1' \
	  --alsologtostderr

and get result below

<img alt="" width="365" height="160" src="https://user-images.githubusercontent.com/1267359/61169224-156dcd00-a58d-11e9-94a3-f9b83be862d4.png">

<img alt="" height="160" src="https://user-images.githubusercontent.com/1267359/61169260-b3fa2e00-a58d-11e9-870e-45a46be2a98b.png">

and best result get episode return -130~-100
<img alt="" height="160" src="https://user-images.githubusercontent.com/1267359/61169270-d8eea100-a58d-11e9-972b-516eebe8de9b.png">

**Comment by witwolf** [comment]
> I can understand ddpg and sac can be twice as slow as tfagents, because for mini_batch_length=2, computation cost are doubled. Currently, this can be alleviated by using a larger mini_batch_length and correspondingly smaller mini_batch_size. And this won't be a big issue for RNN as we will need to use a larger value for mini_batch_length.
> 
> But I don't understand why sac is more than twice as slow as tf-agent.

i made a mistake when compare with sac , debug_summaries was set to True on alf,
and now result seems reasonable , it cost 2~3x  ( tfa cost about 5-6mins and less than previous experiment  because it was taken on a  more powerful machine )

<img height="130" src="https://user-images.githubusercontent.com/1267359/61169789-f45caa80-a593-11e9-8f19-2afe94c7f28c.png">

and i am working on add a simple time profile decorator to statistic and help analysis time cost  ( not work yet , there's problem with  autograph )

**Comment by hnyu** [comment]
Yeah make sure to turn off our summary code for debugging and grads&vars as they will take a long time (see #91 ). Also when you do time profiling in the graph mode, make sure to add dependencies before calling the timer, otherwise the time interval is always very small because of parallelization.
