### ISSUE TITLE
AttributeError: 'collections.OrderedDict' object has no attribute 'is_continuous'

### ISSUE THREAD

**Issue by ipsec** [HorizonRobotics/alf#1079]
Hi, 

Congratulations by excellent project.

I need to use a complex action space with three values.
Value1 discrete between 0 and 2.
Value2 Box starting from 5 to 20 (or greater), int values.
Value3 Box starting from 5 to 20 (or greater), int values.

I'm testing the [Dict](https://github.com/openai/gym/blob/master/gym/spaces/dict.py) action space like this:

```
        self.action_space = spaces.Dict({
            'value1': spaces.Discrete(3),
            'value2': spaces.Box(low=5, high=20, shape=(), dtype=np.int64),
            'value3': spaces.Box(low=5, high=20, shape=(), dtype=np.int64),
        })
```

While running I get wrongs minimum (-1) and maximum (1) values to the Box spaces.

```
I1119 01:05:22.726042 4350281088 policy_trainer.py:332] observation_spec=BoundedTensorSpec(shape=(100,), dtype=torch.float32, minimum=array(-inf, dtype=float32), maximum=array(inf, dtype=float32))
I1119 01:05:22.726506 4350281088 policy_trainer.py:334] action_spec=OrderedDict([('value1',
              BoundedTensorSpec(shape=(), dtype=torch.int64, minimum=array(0), maximum=array(2))),
             ('value2',
              BoundedTensorSpec(shape=(), dtype=torch.int64, minimum=array(-1), maximum=array(1))),
             ('value3',
              BoundedTensorSpec(shape=(), dtype=torch.int64, minimum=array(-1), maximum=array(1)))])
```

The code continues but I'm receiving an error:

```
  File "/Users/fernando/Documents/dev/projects/alf/alf/algorithms/mcts_models.py", line 427, in __init__
    self._dynamics_net = dynamics_net_ctor(
  File "/Users/fernando/Documents/dev/projects/alf/alf/algorithms/mcts_models.py", line 286, in create_simple_dynamics_net
    if not action_spec.is_continuous:
AttributeError: 'collections.OrderedDict' object has no attribute 'is_continuous'
  In call to configurable 'SimpleMCTSModel' (<class 'alf.algorithms.mcts_models.SimpleMCTSModel'>)
  In call to configurable 'MuzeroAlgorithm' (<class 'alf.algorithms.muzero_algorithm.MuzeroAlgorithm'>)
  In call to configurable 'Agent' (<class 'alf.algorithms.agent.Agent'>)
```

How to fix the minimum and maximum values?
How to make Dict space continuous? The method [sample()](https://github.com/openai/gym/blob/590f2504a76fa98f3a734a4d8d45d536e86eb5d5/gym/spaces/dict.py#L95) is returning a OrderedDict object.

**Comment by emailweixu** [comment]
`create_simple_dynamics_net()` can only handle simple action space. For complex action space, you need to implement your own function for creating dynamics_net and pass it as an argument to dynamics_net_ctor when constructing SimpleMCTSModel. This should not be very difficult by using EncodingNetwork.

**Comment by emailweixu** [comment]
There are other parts of mcts_model.py not supporting complex action space. For MCTSModel, the following lines need to changed to handle nested action (by using `alf.nest.map_structure` and/or `alf.utils.dist_utils.compute_log_probability()`)

https://github.com/HorizonRobotics/alf/blob/04eb023a9583109cf9fbc02eff1e9d58aec74127/alf/algorithms/mcts_models.py#L171-L175

For SimplePredictionNet, the following lines need to be changed. You can refer to `ActionDistributionNetwork` to see how to output action distributions for nested action.
https://github.com/HorizonRobotics/alf/blob/04eb023a9583109cf9fbc02eff1e9d58aec74127/alf/algorithms/mcts_models.py#L328-L333

There may be other places that need to changed.

**Comment by emailweixu** [comment]
> ```
> I1119 01:05:22.726042 4350281088 policy_trainer.py:332] observation_spec=BoundedTensorSpec(shape=(100,), dtype=torch.float32, minimum=array(-inf, dtype=float32), maximum=array(inf, dtype=float32))
> I1119 01:05:22.726506 4350281088 policy_trainer.py:334] action_spec=OrderedDict([('value1',
>               BoundedTensorSpec(shape=(), dtype=torch.int64, minimum=array(0), maximum=array(2))),
>              ('value2',
>               BoundedTensorSpec(shape=(), dtype=torch.int64, minimum=array(-1), maximum=array(1))),
>              ('value3',
>               BoundedTensorSpec(shape=(), dtype=torch.int64, minimum=array(-1), maximum=array(1)))])
> ```
> 

It's not clear to me the minimum and maximum are not correct. But you can set a breakpoint in alf_gym_wrappers.tensor_spec_from_gym_space to see what's wrong. 


For discrete action, I recommend you use   space.Discrete instead of Box.

**Comment by ipsec** [comment]
Hi @emailweixu,

I using a map key value structure with Discrete action space (> 5000 actions) now.

Thanks.
