### ISSUE TITLE
alf_config.py in the log directory may not be the one actually used for training

### ISSUE THREAD

**Issue by emailweixu** [HorizonRobotics/alf#1215]
Currently, ALF write alf_config.py after model has been updated. If the conf file has been changed before that, the content in alf_config.py is not same as the one actually used for training.

**Comment by hnyu** [comment]
> Currently, ALF write alf_config.py after model has been updated. If the conf file has been changed before that, the content in alf_config.py is not same as the one actually used for training.

By "if the conf file has been changed before that", do you mean changing it manually (editing), or changing it by the code?

**Comment by emailweixu** [comment]
> > Currently, ALF write alf_config.py after model has been updated. If the conf file has been changed before that, the content in alf_config.py is not same as the one actually used for training.
> 
> By "if the conf file has been changed before that", do you mean changing it manually (editing), or changing it by the code?

Manually.
