### ISSUE TITLE
merge code for off_policy_trainer and on_policy_trainer

### ISSUE THREAD

**Issue by witwolf** [HorizonRobotics/alf#123]
code implementation  for  `off_policy_trainer` and `on_policy_trainer` have much similarity,
we should merge them

**Comment by emailweixu** [comment]
I think they are different enough to warrant separate implementations. Although it's possible to extract some common parts for re-use or put into main.

**Comment by emailweixu** [comment]
We also need to keep in mind that the training process may vary across different algorithms. We should make it not too difficult to customize training.
