### ISSUE TITLE
Locomotion performence is poor

### ISSUE THREAD

**Issue by www2171668** [HorizonRobotics/alf#1255]
Hello. I want to use sac to run locomoton staks. Now, I check Ant-v3, Ant-v2 and other locomotion tasks. As your work in "conf and SAC changes to reproduce reported locomotion results". I never change any parameters to run sac_locomotion_conf, but the performence is poor as following. In SAC paper, Ant performance finally will get 6000. 
![image](https://user-images.githubusercontent.com/49861957/160611274-c311711f-4876-47eb-81a3-f6dcd162b9f0.png)

**Comment by hnyu** [comment]
Hi, let me rerun the task with several random seeds and see how it goes.

**Comment by www2171668** [comment]
Thank you. Mention one thing. The only changed para is num_parallel_environments. I set it to 20.

**Comment by hnyu** [comment]
> Thank you. Mention one thing. The only changed para is num_parallel_environments. I set it to 20.

I see. Yeah setting it to >1 envs will definitely decrease its sample efficiency. This means that now every rollout step generates 20 time steps while the SAC paper (with only 1 env) generates 1 time step every rollout step. So the ratio of training samples to rollout samples is now only 1/20. I suggest setting it back to 1 for reproducing purpose.

In your case, if num of envs=20, then you should probably train it longer (targeting at least 20M steps) to see its final performance.

**Comment by www2171668** [comment]
I get it. Before, I thought num_parallel_environments just influence the traing efficiency, but would not affect the training performence. Thank you very much.

**Comment by hnyu** [comment]
> I get it. Before, I thought num_parallel_environments just influence the traing efficiency, but would not affect the training performence. Thank you very much.

Update:

![image](https://user-images.githubusercontent.com/51248379/160969035-2ec4a2ca-a992-4a22-854a-251286200bce.png)

Out of four random seeds, three are able to get 6000 in 3M steps. One unlucky seed only gets about 3000. (BTW: this run uses grid_search.py for 4 repeats).
