### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by emailweixu** [HorizonRobotics/alf#126]
As the code base become larger, we should have CI test to make sure new changes do not break the tests. https://travis-ci.org/ is a popular site to provide free CI support. This is one example of using travis: https://github.com/PaddlePaddle/PARL/blob/develop/.travis.yml

One CI is available, we can add it as a condition of merge a pull request.

Another thing is to use fixed random seed for tests to make them robuster, otherwise there will be lot of headache.

**Comment by witwolf** [comment]
since job check_stype added in CI ,  code style tools should be unified , tools below are used in our ci job 

    pre-commit==1.17.0 
    cpplint==1.4.4 
    pydocstyle==4.0.0 
    pylint==2.3.1 
    yapf==0.28.0

**Comment by emailweixu** [comment]
Resolved by PR #128

**Comment by emailweixu** [comment]
Can you update CONTRIBUTING.md to include the version of  those code style tools.
