### ISSUE TITLE
Apple M1 GPU - PyTorch "mps" backend support

### ISSUE THREAD

**Issue by ipsec** [HorizonRobotics/alf#1336]
Hi all,

Congrats by excellent project.
PyTorch built a new version with Apple M1 GPUs supported, but they built a new [PyTorch backend called "mps"](https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/).
I was looking your code about how to change to allow mps support and there was a lot of changes to be done.

I ask if is possible to include this new backend without take much of your time. 

Example given of the new backend usage.
```
mps_device = torch.device("mps")

# Create a Tensor directly on the mps device
x = torch.ones(5, device=mps_device)
```

Thanks in advance.

**Comment by emailweixu** [comment]
@ipsec, we don't have any M1 GPU.

There are 16 cases of 'cuda' or "cuda" in the code.  So the change for supporting M1 shouldn't be too difficult.
