### ISSUE TITLE
How to get to the next step the AlfGymWrapper class

### ISSUE THREAD

**Issue by neuronphysics** [HorizonRobotics/alf#1377]
Hello,
I am using `alf` library to collect data from the gym (mujoco) environment.  I have written the following code and I noticed basically that this code never reaches to the end of the episode  for any environment
  ```
import alf_gym_wrapper
import torch
import numpy as np
seed=0
torch.manual_seed(seed)
np.random.seed(seed)
dm_env = gym.spec('HalfCheetah-v2').make()
env = alf_gym_wrapper.AlfGymWrapper(dm_env, discount=0.99)
observation_spec = env.observation_spec()
action_spec = env.action_spec()
def eval_policy_episodes(env, policy, n_episodes):
  """Evaluates policy performance."""
  results = []
  for _ in range(n_episodes):
    time_step = env.reset()
    total_rewards = 0.0
    while not time_step.is_last():
      action = policy(time_step.observation)[0]
      time_step = env.step(action)
      total_rewards += time_step.reward
    results.append(total_rewards)
  results = torch.tensor(results)
  return torch.mean(results).to(dtype=torch.float32), torch.std(results).to(dtype=torch.float32)
```
I looked at the examples and the documentation but I couldn't figure out how I can modify my code to go to the next time step and eventually reaches to the end of the episode. I will appreciate if someone can give me a suggestion.

**Comment by Haichao-Zhang** [comment]
We have some related parts here: https://github.com/HorizonRobotics/alf/blob/pytorch/alf/environments/suite_gym.py

It seems that the time_limit is not applied? For an example, please refer to the following lines:
https://github.com/HorizonRobotics/alf/blob/70e7c3d803a1371e79566893c6b363cf42aa3156/alf/environments/suite_gym.py#L57-L58

https://github.com/HorizonRobotics/alf/blob/70e7c3d803a1371e79566893c6b363cf42aa3156/alf/environments/suite_gym.py#L146-L147

**Comment by hnyu** [comment]
@neuronphysics as Haichao suggested, you probably need the `TimeLimit` wrapper from `alf_wrapper.py`, or try directly doing `gym.make('HalfCheetah-v2')`.

**Comment by Haichao-Zhang** [comment]
Please reopen if you have any further questions.
