### ISSUE TITLE
Incorporating long-term entropy bonus reward in on-policy AC

### ISSUE THREAD

**Issue by hnyu** [HorizonRobotics/alf#139]
For on-policy AC, we have the entropy regularizer E_{\pi}[-log(a_t|s_t)] at every step. As an unbiased estimation, we can simply use the negative log-likelihood -log(a_t|s_t) as an additional reward **added to the computed advantage** towards the end of loss computation. This is essentially a one-step entropy bonus reward where the policy only cares about the single-step bonus. 

We can extend this to long-term entropy maximization by adding -log(a_t|s_t) as instrinsic rewards (just like the ICM rewards) which will be absorbed in the advantage and return computations. A simple derivation will tell us that this is equivalent to the objective of SAC. This could potentially further improve our on-policy AC performance on top of the current single-step entropy bonus.

**Comment by hnyu** [comment]
![Screenshot from 2019-08-05 13-54-52](https://user-images.githubusercontent.com/51248379/62494644-d6e0c200-b788-11e9-97fa-cf6be5353249.png)

**Comment by emailweixu** [comment]
I tried removing entropy as reward in SAC. On bipedal walker, it seems entropy reward does not have any benefit. In the following graph, orange and grey curves do not use entropy reward, blue and red curves uses entropy reward. All of them use entropy regularization in the training cost and adjust the regularization weight using the same way.
![sac_no_entropy_reward](https://user-images.githubusercontent.com/9756952/73584178-7be40b00-444b-11ea-8270-957d33012c91.png)

**Comment by hnyu** [comment]
As I went through [BAIR blog](https://bair.berkeley.edu/blog/2018/12/14/sac/) about SAC:

> In this post, we will view the objective as a grounded way to derive better reinforcement learning algorithms that perform consistently and are sample efficient enough to be applicable to real-world robotic applications, and—**perhaps surprisingly—can yield state-of-the-art performance under the conventional, maximum expected return objective (without entropy regularization) in simulated benchmarks**.

So it seems that the entropy reward can increase the robustness of the policy in the real world where unexpected randomness can happen during testing, which is not the case in simulated benchmarks.

Also, I guess if we use entropy reward, then probably we shouldn't also have the entropy cost. The entropy cost we have currently from A3C is basically a greedy version (only consider horizon length=1) of the entropy reward.
