### ISSUE TITLE
How to get which Vehicle light state of each actor ?

### ISSUE THREAD

**Issue by sk9073** [HorizonRobotics/alf#1404]
I tried using "get_vehicles_light_states()" to get the vehicle's light state for 5 actors that were spawned.

            light_st = world.get_vehicles_light_states()
            print(light_st)

But the output i got was a dictionary with vehicle_Id as key and its light_sate as pair :
I am not sure how to get which indicator is currently turned on if any from the given output . 

![image](https://user-images.githubusercontent.com/59683781/197803676-3957654e-f9e7-49ec-b596-449e32aa3360.png)

**Comment by Haichao-Zhang** [comment]
Hi, all the light states are defined here:
https://github.com/carla-simulator/carla/blob/master/LibCarla/source/carla/rpc/VehicleLightState.h

You can take bitwise and between the returned state with them to decode. 
For example, ``136: 1`` means the ``LowBeam`` light is on for actor ``136``.

**Comment by sk9073** [comment]
Oh got it , Thank you @Haichao-Zhang
