### ISSUE TITLE
Visual network architecture

### ISSUE THREAD

**Issue by Mming11** [HorizonRobotics/alf#1492]
if I want to visualize the neural network architecture used in the **ppg_metadrive_transformer_conf.py** file，what should i do？

**Comment by Haichao-Zhang** [comment]
Hi Thanks for the message.

The procedure to visualize the algorithm architecture of a conf file is as follows:
* intall graphviz: ``sudo apt-get install graphviz``
* run the training for a few epochs
``python  -m alf.bin.train --conf=path_to_conf --root_dir=path_to_results``

The figure ``algorithm_sturcture.png`` will be saved  to the root dir.

Let us know if you have further questions.

**Comment by Mming11** [comment]
sry... I didn't find anything like a png in root dir.

**Comment by Mming11** [comment]
oh, i find this "W0503 23:24:27.788165 140296919340224 policy_trainer.py:111] Need "graphviz" installed if you want to visualize modules".
But i have installed it.
![2023-05-03 23-26-28 的屏幕截图](https://user-images.githubusercontent.com/80202433/235963390-9656d41c-7788-4102-a9af-91be7e207415.png)

**Comment by breakds** [comment]
Hi @Mming11,

The `graphviz` module prompted by `alf` actually means the `graphviz` **python** module. Depending on how you build your python development environment for `alf`, you may need to do so with `poetry add graphviz` or `pip install graphviz`. The package you have installed via `apt` does not provide the python package, at least not directly in your development environment as it appears.

Also, what kind of visualization do you expect?

**Comment by breakds** [comment]
![algorithm_sturcture](https://user-images.githubusercontent.com/1111035/235993967-d84d30b5-6f9e-45de-beec-ce212a8be22e.png)

Here is the visualization that I generated for `ppg_metadrive_transformer`. Hope it helps.

**Comment by Mming11** [comment]
Oh, that's great. Thank you very much!!!
