### ISSUE TITLE
Broken documentation

### ISSUE THREAD

**Issue by emailweixu** [HorizonRobotics/alf#1506]
The documentation for most classes are not generated. For example: https://alf.readthedocs.io/en/latest/api/alf.algorithms.html

Is it possible to make the CI check the documentation is correctly generated?

**Comment by hnyu** [comment]
> The documentation for most classes are not generated. For example: https://alf.readthedocs.io/en/latest/api/alf.algorithms.html
> 
> Is it possible to make the CI check the documentation is correctly generated?

The doc is generated by a RTD server. Even when the doc is broken, the doc build status is usually still 'success'. So it's hard to know the issue by just looking at the building result.
