### ISSUE TITLE
memory leak running examples/icm_mountain_car.sh

### ISSUE THREAD

**Issue by emailweixu** [HorizonRobotics/alf#16]
The memory usage keeps growing during training when running icm_mountain_car.sh as shown in the graph (unit is MB).

![icm_memory](https://user-images.githubusercontent.com/9756952/57342387-a2128f80-70f3-11e9-8e55-05a61e98f7b8.png)

**Comment by witwolf** [comment]
gpu memory oom when running [icm_super_mario](https://github.com/HorizonRobotics/alf/blob/PR_icm_super_mario/alf/examples/icm_super_mario.sh)

![1557923554498](https://user-images.githubusercontent.com/1267359/57775878-a4f32d00-7750-11e9-9404-c68a02de5acd.jpg)

**Comment by witwolf** [comment]
from absl.testing import absltest
    from tf_agents.utils import common as tfa_common
    from tf_agents.environments import suite_gym
    from tf_agents.environments import tf_py_environment
    from absl.testing import parameterized
    import tensorflow as tf
    import treelib
    from pympler import summary, muppy
    
    
    def print_graph(tf_func, *args):
        def _build_tree(tree, op, parent=None):
            node = tree.create_node(op.name, None, parent)
            for input in op.inputs:
                _build_tree(tree, input.op, node.identifier)
    
        graph = tf_func.get_concrete_function(*args).graph
        ops = graph.get_operations()
        tree = treelib.Tree()
        _build_tree(tree, ops[-1])
        tree.show()
    
    
    class Test(parameterized.TestCase, tf.test.TestCase):
    
        @parameterized.parameters(False, True)
        def test_mem_leak(self, use_tf_fuctions):
            tf_env = tf_py_environment.TFPyEnvironment(suite_gym.load('CartPole-v0'))
            if use_tf_fuctions:
                tf_env.reset = tfa_common.function(tf_env.reset)
            init_summary = summary.summarize(
                muppy.get_objects())
            last_summary = init_summary
            for i in range(5):
                tf_env.reset()
                cur_summary = summary.summarize(
                    muppy.get_objects())
                latest_diff = summary._sweep(
                    summary.get_diff(last_summary, cur_summary))
                print("Diff iter %d:%d" % (i, i + 1))
                summary.print_(latest_diff, sort='type')
                cumulative_diff = summary._sweep(
                    summary.get_diff(init_summary, cur_summary))
                # care about probably leaked types
                keys = set(row[0] for row in latest_diff)
                cumulative_diff = [row for row in cumulative_diff if row[0] in keys]
                print("Diff iter 0:%d" % (i + 1))
                summary.print_(cumulative_diff, sort='type')
                last_summary = cur_summary
    
    
    if __name__ == '__main__':
        absltest.main()

TFPyEnvironment should used with tf.functions, otherwise memory leak occurs

![image](https://user-images.githubusercontent.com/1267359/58175579-09733680-7cd3-11e9-8dd5-8eb89163432c.png)

**Comment by bayesian** [comment]
it seems that those objects are very small, might not be the cause of memory leak.

when I switch from internal states observation to include stereo images, it had very bad memory leaks (kswapd dominate cpu usage, other process idles), tf.function setting does not help. I switched to tf 5.22 nightly build.

**Comment by bayesian** [comment]
perhaps related to https://github.com/tensorflow/agents/issues/20
it also points to TFPyEnvironment

**Comment by bayesian** [comment]
actually found out the problem with objgraph memory tool, it is caused by __reduce__ in pickle for numpy.

https://github.com/numpy/numpy/issues/12896

caused by tf_py environment use pickle to send/recv ndarray observations..
