### ISSUE TITLE
multi-gpu training issue

### ISSUE THREAD

**Issue by hnyu** [HorizonRobotics/alf#1632]
It seems that since PR #1625 , multi-gpu training in Hobot breaks down with the error like 'hobot.environments has no module "mj_sim"'. A CMake error regarding `rapid_env_lib` also occurs earlier in this process.

**Comment by le-horizon** [comment]
@hnyu , I can still run tabletop expert training on multi gpus.  Could you send me the config file you run so I can reproduce?

**Comment by hnyu** [comment]
> @hnyu , I can still run tabletop expert training on multi gpus. Could you send me the config file you run so I can reproduce?

You need to first delete rapid env .so file and its build dir? The error only happens if a new .so is built.

**Comment by hnyu** [comment]
Sorry it turns out this issue has nothing to do with ALF. Closed.
