### ISSUE TITLE
Support for Gymnasium Library

### ISSUE THREAD

**Issue by pyorx** [HorizonRobotics/alf#1707]
Hello,

I've noticed that there is currently no support for Gymnasium within the framework.

Could you please let me know if there are any plans to integrate Gymnasium support in the near future?

Thank you for your time and the excellent work on the framework!

Best regards,
Luca

**Comment by hnyu** [comment]
> Hello,
> 
> I've noticed that there is currently no support for Gymnasium within the framework.
> 
> Could you please let me know if there are any plans to integrate Gymnasium support in the near future?
> 
> Thank you for your time and the excellent work on the framework!
> 
> Best regards, Luca

Hi Luca, thanks for you interest. According to my understanding, Gymnasium is a fork of OpenAI gym and the APIs are mostly the same. According to their minimal example:


```python
import gymnasium as gym
env = gym.make("CartPole-v1")

observation, info = env.reset(seed=42)
for _ in range(1000):
    action = env.action_space.sample()
    observation, reward, terminated, truncated, info = env.step(action)

    if terminated or truncated:
        observation, info = env.reset()
env.close()
```

It seems that one can use gymnasium as if it's gym. ALF already supports gym well. You might just need to take a look at this file https://github.com/HorizonRobotics/alf/blob/pytorch/alf/environments/suite_gym.py 

Or is there other API/feature that's available in gymnasium but not in gym?

**Comment by pyorx** [comment]
Hi @hnyu !

Thank you for your response and for pointing me to the **suite_gym.py** file. I agree that Gymnasium is largely backward compatible with Gym. However, Gymnasium offers a few key advantages that could benefit ALF: it has active maintenance, improved error handling, enhanced documentation, and new features (such as updated `reset()` and `step()` methods that return additional information). It also opens up the potential for newer environments and integrations.

To fully support Gymnasium environments in ALF, a small wrapper might be needed, particularly to handle the differences in the `reset()` and `step()` methods' return values (this would also help manage cases where users implement and register their own environments using Gymnasium.).

Thanks again for your consideration!

**Comment by hnyu** [comment]
> Hi @hnyu !
> 
> Thank you for your response and for pointing me to the **suite_gym.py** file. I agree that Gymnasium is largely backward compatible with Gym. However, Gymnasium offers a few key advantages that could benefit ALF: it has active maintenance, improved error handling, enhanced documentation, and new features (such as updated `reset()` and `step()` methods that return additional information). It also opens up the potential for newer environments and integrations.
> 
> To fully support Gymnasium environments in ALF, a small wrapper might be needed, particularly to handle the differences in the `reset()` and `step()` methods' return values (this would also help manage cases where users implement and register their own environments using Gymnasium.).
> 
> Thanks again for your consideration!

@Luke3Py I looked into Gymnasium and found the the major difference regarding the return values of `reset()` and `step()`, in comparison to the old Gym, is that it now supports the differentiation between a normal termination and a timeout termination. 

```python
terminated (bool) – Whether the agent reaches the terminal state (as defined under the MDP of the task) which can be positive or negative. An example is reaching the goal state or moving into the lava from the Sutton and Barto Gridworld. If true, the user needs to call [reset()](https://gymnasium.farama.org/api/env/#gymnasium.Env.reset).

truncated (bool) – Whether the truncation condition outside the scope of the MDP is satisfied. Typically, this is a timelimit, but could also be used to indicate an agent physically going out of bounds. Can be used to end the episode prematurely before a terminal state is reached. If true, the user needs to call [reset()](https://gymnasium.farama.org/api/env/#gymnasium.Env.reset).
```

We've been aware of this issue for the old gym since a long time ago and thus wrote our own [TimeLimit](https://github.com/HorizonRobotics/alf/blob/pytorch/alf/environments/suite_gym.py#L78) wrapper to handle this difference. With this wrapper properly enabled, the returns values of gym's `step()` and `reset()` are guaranteed to be correctly converted to ALF's `TimeStep` structure. 

Besides this, I didn't find Gymnasium offer more new environments or features. So at this moment there is no plan yet to support it in ALF. But you are more than welcome to submit a PR.

**Comment by pyorx** [comment]
Hi @hnyu !

I hope you’re doing well! I wanted to apologize for the delayed response and thank you for your thorough explanation. Your custom `TimeLimit` solution sounds effective in addressing the issue within ALF.

If Gymnasium becomes a necessity for my environment implementations, I’ll consider creating a simple wrapper to manage that situation. I appreciate your openness to a potential PR despite there being no current plans for Gymnasium support in ALF.

Thanks again for your insights!
