### ISSUE TITLE
Refactoring: remove ceate_???_algorithm

### ISSUE THREAD

**Issue by emailweixu** [HorizonRobotics/alf#178]
We should make it possible to directly configure Algorithm from gin instead of relying on create_???_algorithm.
Since we need to pass observation_spec, action_spec, time_spec etc. to many of the the constructors. We can implement several functions: observation_spec(), action_spec(), time_step_spec() to get those specs from gin.

**Comment by witwolf** [comment]
it will make the configurable interface more clearer , i'll do this refactor
