### ISSUE TITLE
can not work with tf.functions

### ISSUE THREAD

**Issue by witwolf** [HorizonRobotics/alf#19]
1）Code Patch: (examples/actor_critic.py)
  
        # driver = PyDriver(
        #     tf_env,
        #     policy,
        #     observers=train_metrics,
        #     max_steps=num_steps_per_iter)

        driver = DynamicStepDriver(
            tf_env,
            policy,
            observers=train_metrics,
            num_steps=num_steps_per_iter)
        # _ = algorithm.variables  # build networks
        driver.run = tfa_common.function(driver.run)

it run success with (use_icm=0): `python actor_critic.py --root_dir=~/tmp/icm/ --num_parallel_environments=1  --gin_param=train_eval.use_icm=0`

but failed with (use_icm=1): `python actor_critic.py --root_dir=~/tmp/icm/ --num_parallel_environments=1  --gin_param=train_eval.use_icm=1`

> TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: ActorDistributionNetwork/CategoricalProjectionNetwork/Categorical/sample/Reshape_1:0
  In call to configurable 'train_eval' (<function train_eval at 0x134018950>)

the behavior was strange since there's nothing special with icm module (`ICMAlgorithm` )

 
and experiments above run success when we build networks before run graph
 `_ = algorithm.variables  # build networks` 

2） training procedure is incorrect in success cases with `tf.functions`

**Comment by witwolf** [comment]
> 2） training procedure is incorrect in success cases with tf.functions

Object mutation or list appends are not reliable in `tf.functions` ([side_effects_in_tffunction](https://www.tensorflow.org/alpha/tutorials/eager/tf_function#side_effects_in_tffunction)) .
As we use list.append to collect train_info (`TrainPolicy._training_info`),  it works unexpected when using `tf.functions` , `len(TrainPolicy._training_info) is 0` and training procedure never happen

**Comment by bayesian** [comment]
I ran into similar issues with tf_agents code, but those problems went always with latest tensorflow nightly build

**Comment by witwolf** [comment]
> I ran into similar issues with tf_agents code, but those problems went always with latest tensorflow nightly build
 
Which build version of tf-nightly-gpu-2.0-preview  (or -nightly-2.0-preview) ?

**Comment by emailweixu** [comment]
Fixed by #21
