### ISSUE TITLE
inoperative config info seems incorrect

### ISSUE THREAD

**Issue by hnyu** [HorizonRobotics/alf#193]
I included "atari.gin" in my gin file to run a job. In TensorBoard "text", I see the following inoperative info:

![Screenshot from 2019-09-26 16-54-34](https://user-images.githubusercontent.com/51248379/65732359-754d1d80-e07e-11e9-9fa3-e9a4cbf0b686.png)

However, as I check these confs are indeed used by my job. Is there any bug here?

**Comment by witwolf** [comment]
<img width=320 src=https://user-images.githubusercontent.com/1267359/65733108-b46f8300-e0ff-11e9-808b-28e9b6547fac.png>

configurations in red rect are using in sub processes (env process ), operative config can not capture them, only record configurations for the main process

do u check  `CategoricalProjectionNetwork.logits_init_output_factor=1e-10` ?

**Comment by witwolf** [comment]
create an eval_env in current process (make sure not wrap env in a new process ) with 
`TrainerConfig.evaluate=True`
`TrainerConfig.eval_interval=INT_MAX`  would be help

**Comment by hnyu** [comment]
> <img alt="" width="320" src="https://user-images.githubusercontent.com/1267359/65733108-b46f8300-e0ff-11e9-808b-28e9b6547fac.png">
> 
> configurations in red rect are used in sub processes (env process ), operative config can not capture them, only record configurations for the main process
> 
> do u check `CategoricalProjectionNetwork.logits_init_output_factor=1e-10` ?

Yes I checked CategoricalProjectionNetwork.logits_init_output_factor. It's 1e-10. For some reason, it's recognized as inoperative.

**Comment by hnyu** [comment]
I found out the reason is that `CategoricalProjectionNetwork` is used in the namescope `alf/`. So actually there is an operative config `actor/CategoricalProjectionNetwork.logits_init_output_factor = 1e-10`. However, the global scope conf is thought to be inoperative.
