### ISSUE TITLE
Tensorboard visualization of alf computation graph

### ISSUE THREAD

**Issue by emailweixu** [HorizonRobotics/alf#201]
We should support this so that it's easier to examine model. This is the doc on how to do it
https://www.tensorflow.org/tensorboard/graphs#graphs_of_tffunctions

Additional benefits is that it also has CPU and GPU usage statistics, which might be very useful.

**Comment by witwolf** [comment]
i tried to  implement this at commit [83459fe
](https://github.com/HorizonRobotics/alf/commit/83459fe32c5994f168ecfedcbc70a4fd22ca7156),   and it work fine for sac , ddpg examples , but got empty graph for ac , ppo , still do not know why .

**Comment by hnyu** [comment]
@witwolf  Are you still working on this issue? I think it's important to have this feature for debugging.

**Comment by witwolf** [comment]
No,  

 it has problem with tracing computation  graph is some cases  mentioned above and I have no clue about what's going on here for now . And i think the computation graph and profiler are not much readable and friendly for debugging   

- Computation Graph


<img width="256" alt="WeChatWorkScreenshot_73ee7bbb-268f-4692-99b9-ed92e2e14962" src="https://user-images.githubusercontent.com/1267359/68442065-e6016100-020a-11ea-96d2-0ed56f32d2ee.png">  

<img width="256" alt="WeChatWorkScreenshot_a6467971-78ed-475c-8a3c-3ffecdf41a2b" src="https://user-images.githubusercontent.com/1267359/68442054-e00b8000-020a-11ea-8909-b57be1ca11d6.png">

- Profiling

<img width="256" alt="WeChatWorkScreenshot_edc46f17-ef33-4e6d-a41e-a4c05d23b977" src="https://user-images.githubusercontent.com/1267359/68442072-eb5eab80-020a-11ea-9a63-f33c87674416.png">

**Comment by hnyu** [comment]
> > @witwolf Are you still working on this issue? I think it's important to have this feature for debugging.
> 
> No,
> 
> it has problem with tracing computation graph is some cases mentioned above and I have no clue about what's going on here for now . And i think the computation graph and profiler are not much readable and friendly for debugging
> 
> * Computation Graph
> 
> <img alt="WeChatWorkScreenshot_73ee7bbb-268f-4692-99b9-ed92e2e14962" width="256" src="https://user-images.githubusercontent.com/1267359/68442065-e6016100-020a-11ea-96d2-0ed56f32d2ee.png">
> 
> <img alt="WeChatWorkScreenshot_a6467971-78ed-475c-8a3c-3ffecdf41a2b" width="256" src="https://user-images.githubusercontent.com/1267359/68442054-e00b8000-020a-11ea-8909-b57be1ca11d6.png">
> 
> * Profiling
> 
> <img alt="WeChatWorkScreenshot_edc46f17-ef33-4e6d-a41e-a4c05d23b977" width="256" src="https://user-images.githubusercontent.com/1267359/68442072-eb5eab80-020a-11ea-9a63-f33c87674416.png">

OK, never mind. I expected a much better visualization than this.

**Comment by emailweixu** [comment]
No longer adding feature to the tf version
