### ISSUE TITLE
ParallelPyEnvironment will cause sys.exit() to hang after main() finishes

### ISSUE THREAD

**Issue by hnyu** [HorizonRobotics/alf#206]
I've tested for quite some time to pin down an issue (reason unknown at this moment) that once we created tf_agents' ParallelPyEnvironment in main(), after the code finishes, sys.exit() will hang forever without releasing the GPU memory (running in CPU mode also has this hanging issue). This makes grid_search.py fail. The minimal re-producible example is to replace the `train_eval(root_dir)` function with the following:

```
@gin.configurable
def train_eval(root_dir):
    env = create_environment()
    env.pyenv.close()
``` 
and run any training job. The script will never exit. 

And I have located the issue exactly at sys.exit(main(argv)) in absl's app.py. It's more like an issue happened inside sys.exit() rather than in absl's code. 

@witwolf  When you ran grid_search.py, did you ever have such a problem?

**Comment by witwolf** [comment]
what are the parameters (gin configurations )  used for create_environment ?
There is indeed a problem with `wrap_with_process=True` , but it only happen with `suite_socialbot.load`  and  `suite_mario.load` when `num_parallel_environments=1`

**Comment by witwolf** [comment]
> what are the parameters (gin configurations ) used for create_environment ?
> There is indeed a problem with `wrap_with_process=True` , but it only happen with `suite_socialbot.load` and `suite_mario.load` when `num_parallel_environments=1`

The innermost process is not joined ,i will fixed this

**Comment by hnyu** [comment]
> what are the parameters (gin configurations ) used for create_environment ?
> There is indeed a problem with `wrap_with_process=True` , but it only happen with `suite_socialbot.load` and `suite_mario.load` when `num_parallel_environments=1`

Yes, the issue only happens if wrap_with_process=True (I also set it to True for num_parallel_environments>1). After I set it to False, then it works. Thanks for finding out the reason.
