### ISSUE TITLE
TrainTest fails sometimes

### ISSUE THREAD

**Issue by hnyu** [HorizonRobotics/alf#222]
======================================================================
FAIL: test_ppo_cart_pole (bin.train_test.TrainTest)
test_ppo_cart_pole (bin.train_test.TrainTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ALF/alf/bin/train_test.py", line 100, in test_ppo_cart_pole
    self._test_train('ppo_cart_pole.gin', _test_func)
  File "/ALF/alf/bin/train_test.py", line 126, in _test_train
    assert_func(episode_returns, episode_lengths)
  File "/ALF/alf/bin/train_test.py", line 97, in _test_func
    self.assertGreater(np.mean(returns[-2:]), 198)
AssertionError: 197.8499984741211 not greater than 198

@witwolf It seems that the determinism isn't working as expected? There are some other cases failed sometimes, and I have to manually restart the testing job each time.

**Comment by witwolf** [comment]
Random seed is not fixed for environment ,  It is a possible reason that train test fails sometimes. 
Any other case fails except TrainTest ?

**Comment by witwolf** [comment]
And there are other reasons:
1. multiple threads are used for parallelism between independent operations in tf 
2. the order of running  op are uncertain (when they have no dependencies)

perharps we should set  `tf.config.threading.set_inter_op_parallelism_threads(1)` for unittest

**Comment by hnyu** [comment]
> Random seed is not fixed for environment , It is a possible reason that train test fails sometimes.
> Any other case fails except TrainTest ?

Sometimes the SAC case will also fail.

**Comment by hnyu** [comment]
> And there are other reasons:
> 
> 1. multiple threads are used for parallelism between independent operations in tf
> 2. the order of running  op are uncertain (when they have no dependencies)
> 
> perharps we should set `tf.config.threading.set_inter_op_parallelism_threads(1)` for unittest

I think for unittest, to avoid the parallelism, we can set num_envs=1 and not use async-off policy training.

**Comment by witwolf** [comment]
It's hard to make the training have deterministic result, i did some experiments
with fixed seed for tf and environments  and set `inter_op_parallelism_threads` to 1 , the result shows it still has the probability of getting different results

<img src='https://user-images.githubusercontent.com/1267359/66881958-35cd7d80-effb-11e9-82b7-0c9194495bcc.png' height=128><img  src='https://user-images.githubusercontent.com/1267359/66881903-0caced00-effb-11e9-805f-0719d3492f3a.png' height=128>

Personally think, it's ok when some unittest fails

**Comment by hnyu** [comment]
> It's hard to make the training have deterministic result, i did some experiments
> with fixed seed for tf and environments and set `inter_op_parallelism_threads` to 1 , the result shows it still has the probability of getting different results
> 
> <img alt="" height="128" src="https://user-images.githubusercontent.com/1267359/66881958-35cd7d80-effb-11e9-82b7-0c9194495bcc.png"><img alt="" height="128" src="https://user-images.githubusercontent.com/1267359/66881903-0caced00-effb-11e9-805f-0719d3492f3a.png">
> 
> Personally think, it's ok when some unittest fails

OK, I thought the reason why we changed unittest to tf.unittest is because of the determinism it provides. Then maybe next time the test threshold should be less strict.

**Comment by hnyu** [comment]
So if everything has fixed random seeds, then the only stochasticity is from CPU scheduling for parallelism, right? What about we use eager mode for unittests?

**Comment by emailweixu** [comment]
Using eager mode will make the test much longer.
Perhaps the game itself has some randomness inside?

**Comment by hnyu** [comment]
> Using eager mode will make the test much longer.
> Perhaps the game itself has some randomness inside?

I think @witwolf tried setting the seeds of environments deterministically. Even so, the results are nondeterministic.
