### ISSUE TITLE
alf build failing

### ISSUE THREAD

**Issue by Haichao-Zhang** [HorizonRobotics/alf#232]
This is the current status on the github page:

![image](https://user-images.githubusercontent.com/21375027/66889931-025a0700-ef99-11e9-85ed-ca58deefd7ea.png)

Looking into travis logs, the following one fails
![image](https://user-images.githubusercontent.com/21375027/66889840-beff9880-ef98-11e9-833d-138924d492a9.png)

**Comment by hnyu** [comment]
See #222 . There is some stochasticity in the training every time. I think we should make the test case less strict.
