### ISSUE TITLE
A possible logo for ALF?

### ISSUE THREAD

**Issue by hnyu** [HorizonRobotics/alf#234]
@Haichao-Zhang  Maybe use your image editing skills.

**Comment by hnyu** [comment]
![alf_logo](https://user-images.githubusercontent.com/51248379/66956682-b00cfa80-f019-11e9-93ae-07836fab656c.png)

A smart-mouthed creature, ALF (aka Alien Life Form)

**Comment by hnyu** [comment]
<img width="941" alt="Screen Shot 2019-11-26 at 9 33 22 PM" src="https://user-images.githubusercontent.com/51248379/69696441-86250a00-1094-11ea-83b2-366a663aea18.png">

@Haichao-Zhang and @emailweixu , how about this one?

**Comment by emailweixu** [comment]
Wow! You drew the picture by yourself?

**Comment by hnyu** [comment]
> Wow! You drew the picture by yourself?

It was adapted from some online auto logo maker. To actually use it I guess we need to pay for the icon.
