### ISSUE TITLE
segmentation fault for play with socialbot environments

### ISSUE THREAD

**Issue by emailweixu** [HorizonRobotics/alf#240]
The problem can be fixed if wrap_process=True is used in the following line (and remove the next line)
https://github.com/HorizonRobotics/alf/blob/d58103f299558f5fdeae218bd23515aed5c9b557/alf/environments/utils.py#L158-L159

**Comment by hnyu** [comment]
I have no idea what's going here. I tested self._eval_env without being wrapped, and it worked well. It seems that for playing, the innermost Python environment crashes for either reset() or step(), as I traced the error back to the FrameStack wrapper.

**Comment by witwolf** [comment]
I  tested it on my machine and did not encounter such a problem.   what is the details ?

**Comment by hnyu** [comment]
> I tested it on my machine and did not encounter such a problem. what is the details ?

Make sure to pull the newest version where play.py creates an environment with `nonparallel=True`. For example, after you train a checkpoint for ac_simple_navigation.gin and load it to play, the segfault will occur.

**Comment by hnyu** [comment]
Or perhaps for now we can just add a hack of always wrapping SocialBot environments. But this will also show incorrect gin information for them.

**Comment by witwolf** [comment]
found out the reason  is that gazebo operations on an instance (creation, reset, step ...)  can not run in multiple thread .   I'll fix this issue
