### ISSUE TITLE
missing curves and gifs in README

### ISSUE THREAD

**Issue by hnyu** [HorizonRobotics/alf#281]
We are missing training curves and GIFs showing the trained agent play in the following two environments in the README file:

"Simple navigation with visual input. Follow the instruction at SocialRobot to install the environment."
and
"PR2 grasping state only. Follow the instruction at SocialRobot to install the environment."

@witwolf  and @Jialn Maybe these are easy for you guys to add?

**Comment by Jialn** [comment]
OK, I'll add them.
