### ISSUE TITLE
remove all specs

### ISSUE THREAD

**Issue by hnyu** [HorizonRobotics/alf#335]
I believe that specs makes our framework strong-type which is good for avoiding mistakes but also makes code much less flexible and more verbose (not pythonic). The main reasons for having specs are two:

1) tf_agents networks require specs to initialize
2) a replay buffer requires specs to allocate memories in `__init__`

For 1), probably we can rewrite some networks (keras doesn't require specs); for 2) when we create a replay buffer, we should input an example of experience and let the replay buffer class extract the specs internally. 

Am I missing other reasons for specs?

**Comment by emailweixu** [comment]
state spec seems unavoidable because it is the input to predict/rollout/train_step. And without the spec, it cannot be constructed.

**Comment by hnyu** [comment]
Instead of creating states in the highest level, we can let sub-algorithms create their own initial states given `time_step.StepType`. Each sub-algorithm will of course know its state dimension if a state is needed.
