### ISSUE TITLE
TTP: ActorDistributionNetwork

### ISSUE THREAD

**Issue by emailweixu** [HorizonRobotics/alf#340]
Depends on:

- [ ] #338 CategoricalProjectionNetwork
- [ ] #339 NormalProjectionNetwork
- [ ] #345 EncodingNetwork

**Comment by hnyu** [comment]
While we will try to minimize the use of specs, in places where we have to use, I think we can directly rely on `gym.spaces.discrete.Discrete` for our network modules.
