### ISSUE TITLE
TTP: checkpoint handling

### ISSUE THREAD

**Issue by hnyu** [HorizonRobotics/alf#358]

**Comment by emailweixu** [comment]
Seems that torch.nn.Parameter serves similar function as tf.Variable. torch.save() can handle the attributes of nn.Module if they are Parameter
Ref:
https://pytorch.org/docs/stable/nn.html?highlight=nn%20parameter#torch.nn.Parameter

**Comment by emailweixu** [comment]
Solved by #376
