### ISSUE TITLE
Make metrics work with Experience

### ISSUE THREAD

**Issue by emailweixu** [HorizonRobotics/alf#390]
With the current design, metric observes Experience instead of TimeStep. See PR_Trainer #380

**Comment by emailweixu** [comment]
Here is the code segments:
https://github.com/HorizonRobotics/alf/blob/a9d0292386b9722717b6440fe7d08419e4110c0d/alf/algorithms/rl_algorithm.py#L533-L534

**Comment by le-horizon** [comment]
Will it be too much for metrics to access policy_step and policy_state?
Should we have a leaner structure like Trajectory in tf_agents?  https://github.com/tensorflow/agents/blob/master/tf_agents/trajectories/trajectory.py#L35

**Comment by emailweixu** [comment]
We have other observers (replay buffer) which need experience. It's better to have a uniform interface for the observer. You can always ignore unrelated information.
