### ISSUE TITLE
Better histogram for the summary of discrete action

### ISSUE THREAD

**Issue by emailweixu** [HorizonRobotics/alf#43]
At alf.utils.common.add_action_summaries, tf.summary.histogram does not generate good histogram for discrete actions. As we know the min and max of the discrete action, we should generate a histogram with the known number of buckets and with the right min and max.

**Comment by witwolf** [comment]
example of  Discrete(10) action histogram 

![image](https://user-images.githubusercontent.com/1267359/59854169-fb353a80-93a4-11e9-8693-bb511dab712f.png)
