### ISSUE TITLE
Naive/Parallel Networks load_state_dict bug

### ISSUE THREAD

**Issue by jesbu1** [HorizonRobotics/alf#552]
In the latest pytorch branch, when using a parallel network and the `observation_input_preprocessors` includes an `EmbeddingPreprocessor`,  this error occurs:

`  File "/home/jessezhang/alf-private/alf/utils/common.py", line 150, in get_target_updater
    target_model.load_state_dict(model.state_dict())
  File "/home/jessezhang/miniconda3/envs/alf-private/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NaiveParallelNetwork:
        Missing key(s) in state_dict: "_networks.1._obs_encoder._input_preprocessor_modules.0._embedding_net.weight".`

It seems the input_preprocessor embedding_net is not copied over correctly when making it parallel.

**Comment by jesbu1** [comment]
@Haichao-Zhang @hnyu please take a look at this, thanks!

**Comment by Haichao-Zhang** [comment]
Looking into it @jesbu1

**Comment by Haichao-Zhang** [comment]
For now you can simply pull https://github.com/HorizonRobotics/alf/pull/554 and you should be able to train. Feel free to reopen if you encounter any further problems.

**Comment by Haichao-Zhang** [comment]
There might be  some other issues and working on it.

**Comment by Haichao-Zhang** [comment]
#554 is one way to solve the reported problem and I have verified on my self-constructed problem.
