### ISSUE TITLE
Figures for evaluation metric against the number of environmental steps

### ISSUE THREAD

**Issue by emailweixu** [HorizonRobotics/alf#64]
For RL, we need to have figure showing the performance with respect to the number of training environment steps. Currently, we only have the figures of metrics vs. global steps

**Comment by witwolf** [comment]
`Metrics_vs_EnvironmentSteps`  and `Metrics_vs_NumberOfEpisodes` already exist in summary ?

**Comment by emailweixu** [comment]
We need to show the evaluation metrics vs. training environmental steps. Metrics_vs_EnvironmentSteps and Metrics_vs_NumberOfEpisodes are only for training right now
