### ISSUE TITLE
alf configurable doesn't handle variable arguments defined in a base class

### ISSUE THREAD

**Issue by hnyu** [HorizonRobotics/alf#809]
In the following case:

```
@alf.configurable
class A(object):
    def __init__(self, x):
        self._x = x


@alf.configurable
class B(A):
    def __init__(**kwargs):
        super(B, self).__init__(**kwargs)
```

When writing an alf conf file, I can't do 

```
alf.config('B', x=1)
```

Because it will report that `B` doesn't have an argument `x`. However, the same thing can be done with gin-config.

**Comment by emailweixu** [comment]
Currently alf.config does not support any kind of positional or keyword vargs.
