### ISSUE TITLE
async_ppo_bullet_humanoid.gin not running

### ISSUE THREAD

**Issue by jkan67** [HorizonRobotics/alf#854]
I was just wondering when this example will be able to run?

**Comment by hnyu** [comment]
> I was just wondering when this example will be able to run?

Hi @jkan67 , `async_ppo_bullet_humanoid.gin` belongs to legacy code that uses Tensorflow. We've converted the majority of ALF from TF to PyTorch for quite some time, but the async training part has not been rewritten yet. 

If you just want to run PPO on bullet humanoid, currently we suggest running `examples/ppo_bullet_humanoid.gin` which is the synchronous version (batched environment). 

Generally async training might result in shorter wall-clock time but less sample efficiency. So even with the old TF version we didn't end up using the async training pipeline much. 

Let us know if you indeed want to run async training on ALF and we will consider adding it to our job list.

**Comment by hnyu** [comment]
Also we will update the humanoid example in README to the synchronous working version. @emailweixu

**Comment by jkan67** [comment]
Yeah, getting the async training on ALF would be great. A shorter wall-clock time would work better for the project I am working on. Really cool what you guys are doing!
