### ISSUE TITLE
summarize_grads_and_vars and debug_summaries are very slow

### ISSUE THREAD

**Issue by hnyu** [HorizonRobotics/alf#91]
In the PPO humanoid example, these two summaries will take roughly 3 seconds per training update while the training update itself is only about 2 seconds.

**Comment by emailweixu** [comment]
We can adjust the summary interval. We need to have something to measure how much time is spent on environment.step, predict, training, summary, and evaluation so that we can make right adjustment.

**Comment by hnyu** [comment]
Is it possible to optimize the summary code?

**Comment by witwolf** [comment]
`summary interval`  do not help , it only reduce the frequency of `write to file` ,  computation for data (particular histogram data ..)  , serialization for metadata etc has no reduction， and this part can be optimized at least

**Comment by hnyu** [comment]
Close this issue for #124

**Comment by emailweixu** [comment]
#120 also helps alleviate this issue
