### ISSUE TITLE
Allow executing train and play outside alf/examples/

### ISSUE THREAD

**Issue by breakds** [HorizonRobotics/alf#914]
There is currently a restriction that we have to run the program from within `alf/examples` (or, the directory that directly contains the entry point `.gin` file). This is bad especially for development phase when the recommended way is to run `python -m alf.bin.train` from the repo's root.

## Root Cause

The directory of the entry point `.gin` file should be added to the search path by default IMHO, but it is not. This means that e.g. `include ddpg.gin` will fail if the current working directory is not `alf/examples/`.

## Solution

Whenever calling the parser of gin, we can add the directory of the entry point `.gin` file to the search path with `gin.add_config_file_search_path()`. Therefore `include ddpg.gin` will always succeed when you specify `--gin_file alf/examples/ddpg_pendulum.gin` for example.

## How to Verify the Fix

From the root of the `alf` repo run

``` bash
python -m alf.bin.train --root_dir ~/tmp/pendulum --gin_file alf/examples/ddpg_pendulum.gin
```

Previously this would fail because `ddpg.gin` is not found. It succeeds after the fix.

**Comment by hnyu** [comment]
*.gin file are outdated. Now we suggest using *_conf.py. In these alf conf files, it is recommended to not use relative path but always import using `alf.xxx.yyy`. By doing so, there will be no restriction of where to launch the training or playing, and it's also friendly for playing with snapshot. See 

https://alf.readthedocs.io/en/latest/notes/knowledge_base.html#snapshot

for details.

**Comment by breakds** [comment]
Good to know! Thanks for the reference, @hnyu ! I am going to close this then.

**Comment by breakds** [comment]
I originally thought `.gin` is the new and recommended way. Really appreciate the clairification.
