### ISSUE TITLE
Decouple environment creation and configuration file parsing

### ISSUE THREAD

**Issue by breakds** [HorizonRobotics/alf#930]
# Motivation

In the current implementation, environment processes are created at the moment when the configuration is being parsed/loaded. I would propose to decouple those two because:

1. In the situation when we want to start multiple trainer to run training in parallel, it is preferred that configuration is parsed and loaded first, and each trainer process will start the environments by themselves. We need an option to separate configuration parsing and environment process creation.
2. For readability, it is more clear if `parse_conf_file` does not create the environment under the hood. In fact, explicitly creating them seems more clear.

# Goal

+ [ ] Separate the concept of `configuration parsing` and `environment creation` in the current implementation.
+ [ ] Such change should be transparent to most of the alf developers
+ [ ] Update the related documentation
+ [ ] Test and verify the change

**Comment by hnyu** [comment]
I think there is a very complicated reason why creating env is inside parse_conf_file. I suggest asking @emailweixu first before making any change. It should be related to how alf config works and env random seed initialization.

**Comment by breakds** [comment]
Thanks for the reminder. Yep I understand that this is related to the seed. Will confirm with @emailweixu.

**Comment by breakds** [comment]
Closing this because it depends on retiring the `.gin` files completely (or to put it in another way, waiting for the retirement of `.gin` is an easier alternative). Will re-open once that is done.
