### ISSUE TITLE
ModuleNotFoundError: No module named 'cnest'

### ISSUE THREAD

**Issue by www2171668** [HorizonRobotics/alf#967]
When I test examples，a problem occures. "ModuleNotFoundError: No module named 'cnest'"
How can I deal with it? Thanks

**Comment by hnyu** [comment]
Hi, first you should make sure that under `alf/nest/cnest` there is a compiled cnest .so file. If there is no .so file, then it means the cnest.cpp is not compiled yet. Make sure you do `pip install -e .` first.

If there is a .so file, then there are two ways to solve the issue:
1. export the path `alf/nest/cnest` to your PYTHONPATH
2. `pip install -e ./alf/nest/cnest`

**Comment by breakds** [comment]
> Hi, first you should make sure that under `alf/nest/cnest` there is a compiled cnest .so file. If there is no .so file, then it means the cnest.cpp is not compiled yet. Make sure you do `pip install -e .` first.
> 
> If there is a .so file, then there are two ways to solve the issue:
> 
> 1. export the path `alf/nest/cnest` to your PYTHONPATH
> 2. `pip install -e ./alf/nest/cnest`

Maybe we should split it from alf and publish it to pypi?

**Comment by hnyu** [comment]
> > Hi, first you should make sure that under `alf/nest/cnest` there is a compiled cnest .so file. If there is no .so file, then it means the cnest.cpp is not compiled yet. Make sure you do `pip install -e .` first.
> > If there is a .so file, then there are two ways to solve the issue:
> > 
> > 1. export the path `alf/nest/cnest` to your PYTHONPATH
> > 2. `pip install -e ./alf/nest/cnest`
> 
> Maybe we should split it from alf and publish it to pypi?

I think separating cnest from ALF is a good idea. The cpp code hasn't been changed for over a year, and I don't think we need to change it in the near future. It will be clearer for ALF's setup.py. 

I don't have any experience of publishing to pypi. Feel free to do that if you want to.

**Comment by www2171668** [comment]
Thank you. I know the problem. Win10 cant compile the cpp file.  Linux is OK.
