### ISSUE TITLE
Incorporate `procgen` environments into alf

### ISSUE THREAD

**Issue by breakds** [HorizonRobotics/alf#984]
# Motivation

In PPG and maybe other baseline algorithms the authors use [procgen](https://github.com/openai/procgen) as the benchmarking environment. To be able to test our implementations and algorithms on such environment as well, we should add procgen into the suite of environments as well.

Also, I would like to take this opportunity to learn a bit more into details about how environment works with algorithms in alf.

# Goals

1. [x] Package procgen and be able to run procgen environments
2. [x] Be able to train algorithms with procgen
3. [x] Be able to play trained model
4. [x] Be able to record the play of trained model
5. [ ] Create a set of procgen examples in alf

**Comment by hnyu** [comment]
FYI, I plan to write the environment chapter tomorrow.

**Comment by breakds** [comment]
Though procgen itself uses `gym3` interface, fortunately they provide a `gym` wrapper as well. This means that we can use `gym_suite` to load procgen environments e.g. 

```python
alf.config(
    'create_environment',
    env_name='procgen:procgen-chaser-v0',
    num_parallel_environments=8)
```

Based on their official README, the `gym3` version is vectorized and is said to be faster. Without looking into their implementation I doubt using `gym` will be too much slower as I thought the vectorization is mainly used for simulating the environments internally.

**Comment by breakds** [comment]
> FYI, I plan to write the environment chapter tomorrow.

Thanks Haonan! I peeked into the outline of the tutorial and know that there will be on chapter about this. Looking forward to it!

**Comment by breakds** [comment]
Currently the algorithm can pick up the observations in 64 x 64 resolution, which looks like

![bigfish_000](https://user-images.githubusercontent.com/1111035/130538319-4c0dd6d1-a66b-442d-aceb-1cb59ccba40a.png)

![chaser](https://user-images.githubusercontent.com/1111035/130538329-215c0f71-686f-4596-b85f-6c7da0fcd93d.png)

This is clearly downsampled from the original procgen frames. However, I checked the openai's implementation of PPG and confirmed that they are using 64 x 64 resolution as well, so that I will keep it like this.

**Comment by breakds** [comment]
Now I was able to train on procgen environments and play with the trained model, working around the gym3 issue with a special wrapper (thanks to @hnyu 's suggestion).

Video recording in `alf.bin.play` is still not working as expected and I am working on solving it right now.

**Comment by breakds** [comment]
After digging a bit about `gym3`, I found [this](https://github.com/openai/gym3/blob/4c3824680eaf9dd04dce224ee3d4856429878226/docs/gym3-for-gym-users.md) which sheds light on how to fixing the recording. The rendered `rgb_array` image is actually at 

```python
self.wrapped_env().env.get_info()[0]['rgb']
```

Tested that that this makes recording work again. Example:

https://user-images.githubusercontent.com/1111035/130878129-79ceb8c3-2d7f-4c6e-a0a0-acf69e50cef3.mp4

**Comment by breakds** [comment]
This is now merged. Closing this issue.
