### ISSUE TITLE
Implement batched gym3 wrapper for procgen

### ISSUE THREAD

**Issue by breakds** [HorizonRobotics/alf#996]
# Motivation

`gym3` based `procgen` environments support vectorization (batched) mode natively. However, we are not taking advantages of that in the current implementation, where `ParallelAlfEnvironment` create a single process for each of the instance. This is a waste of both space (memory) and time.

See [gym3 design justifications](https://github.com/openai/gym3/blob/4c3824680eaf9dd04dce224ee3d4856429878226/docs/design.md).

# Proposed Solution

Implement a `gym3` wrapper that does the batch natively (instead of via `ParallelAlfEnvironment`).

# Goals

1. [ ] Implement the `AlfGym3Wrapper`
2. [ ] Unit tests
3. [ ] Makes sure that training and play works
4. [ ] Reduce the Memory consumption from 30GB by at least half when training with 64 environments.
5. [ ] Support `reset` and `seed` properly

**Comment by hnyu** [comment]
You can avoid using ParallelAlfEnvironment by directly wrap gym3 environments with AlfEnvironment. See CarlaEnvironment for an example. The load() function should have `load.batched=True`.

**Comment by breakds** [comment]
> You can avoid using ParallelAlfEnvironment by directly wrap gym3 environments with AlfEnvironment. See CarlaEnvironment for an example. The load() function should have `load.batched=True`.

Yes, that is exactly the approach I am pursuing at this moment.

**Comment by breakds** [comment]
Currently have a draft version that can start training. However this morning I found the training stuck at 50th iteration (at evaluation). My guess is that evaluation is starting another environment which might trigger some bug I did not realize. Investigating.

**Comment by breakds** [comment]
So this comes from 

1. lack of `TimeLimit`, so that one episode in `evaluation` can be infinitely long.
2. However the chance of the above scenario should be rare for certain environments, after further investigation, the problem comes from not setting the `step type` to `LAST` correctly.

**Comment by breakds** [comment]
As a note, based on `procgen`'s source code, sending `-1` is one way to trigger a reset:

https://github.com/openai/procgen/blob/master/procgen/src/game.cpp#L124

**Comment by breakds** [comment]
Closing as the relevant PRs are all merged.
